services:
  db:
    image: postgres:16-alpine
    container_name: impressa_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: impressa_db
    ports:
      - "5432:5432"
    volumes:
      - impressa_pgdata:/var/lib/postgresql/data

volumes:
  impressa_pgdata:
