import type { LegalDoc } from "@/components/amplivanta/legal-document";

export const LEGAL_DOCS: Record<string, LegalDoc> = {
  privacy: {
    breadcrumbLabel: "Privacy Policy",
    title: "Amplivanta Privacy Policy",
    intro:
      "This Privacy Policy explains how Amplivanta Inc. and its affiliates (“Amplivanta”, “we”, “us”, or “our”) collect, use, disclose, and protect your information when you use our website, platforms, products, and services (collectively, the “Services”).",
    updated: "August 14, 2026",
    sections: [
      { heading: "Information We Collect", body: "We collect information you provide directly, information automatically collected, and information from third parties. This includes personal data (such as contact details, account information, and communications), usage data, device and log data, and cookies or similar technologies." },
      { heading: "How We Use Information", body: "We use information to provide, operate, and improve our Services; process transactions; communicate with you; personalize your experience; ensure security; comply with legal obligations; and for other purposes disclosed at the time of collection." },
      { heading: "How We Share Information", body: "We do not sell your personal data. We may share information with service providers, business partners, affiliates, and as required by law or to protect rights and safety. Any third parties are contractually obligated to protect your information and use it only for authorized purposes." },
      { heading: "International Data Transfers", body: "We may transfer information to countries outside your own, including to the United States. We implement appropriate safeguards, such as Standard Contractual Clauses, to ensure your data is protected in accordance with this Policy and applicable laws." },
      { heading: "Data Security", body: "We use industry-standard technical, administrative, and physical safeguards to protect your information against unauthorized access, loss, misuse, alteration, or disclosure. However, no method of transmission over the internet or electronic storage is 100% secure." },
      { heading: "Your Rights & Choices", body: "Depending on your location, you may have rights to access, correct, delete, or restrict processing of your personal data, and to data portability or object to processing. You can also manage cookies through your browser settings. To exercise your rights, contact us using the details below." },
      { heading: "Cookies & Tracking Technologies", body: "We use cookies and similar technologies to enhance your experience, analyze usage, and support marketing efforts. You can control cookies via your browser settings. See our Cookie Policy for details." },
      { heading: "Children’s Privacy", body: "Our Services are not intended for children under the age of 13 (or the applicable age in your jurisdiction). We do not knowingly collect personal data from children. If we learn we have collected such data, we will delete it promptly." },
      { heading: "Changes to This Policy", body: "We may update this Privacy Policy from time to time. We will notify you of material changes by posting the updated policy on our website and updating the “Last updated” date." },
      { heading: "Contact Us", body: "If you have questions or concerns about this Privacy Policy or our data practices, please contact us at privacy@amplivanta.com." },
    ],
  },
  terms: {
    breadcrumbLabel: "Terms of Service",
    title: "Amplivanta Terms of Service",
    intro: "These Terms of Service (“Terms”) govern your access to and use of Amplivanta’s website, platforms, and services. By using the Services you agree to these Terms.",
    updated: "August 14, 2026",
    sections: [
      { heading: "Acceptance of Terms", body: "By accessing or using the Services, you agree to be bound by these Terms and our Privacy Policy. If you are using the Services on behalf of an organization, you represent that you have authority to bind that organization." },
      { heading: "Accounts & Eligibility", body: "You must provide accurate registration information and keep it current. You are responsible for safeguarding your credentials and for all activity under your account." },
      { heading: "Acceptable Use", body: "You agree not to misuse the Services, including by attempting to disrupt them, access them without authorization, infringe intellectual property, or use them for unlawful purposes." },
      { heading: "Subscriptions & Billing", body: "Paid plans are billed in advance on a monthly or annual basis. Fees are non-refundable except as required by law or expressly stated. You can change or cancel your plan subject to the terms of your plan." },
      { heading: "Intellectual Property", body: "Amplivanta and its licensors retain all rights in the Services. You retain ownership of the content you submit, granting us a limited license to operate the Services." },
      { heading: "Termination", body: "We may suspend or terminate access for violations of these Terms. You may stop using the Services at any time; certain provisions survive termination." },
      { heading: "Disclaimers & Limitation of Liability", body: "The Services are provided “as is” without warranties of any kind. To the maximum extent permitted by law, Amplivanta’s liability is limited as described in these Terms." },
      { heading: "Changes to These Terms", body: "We may modify these Terms from time to time. Material changes will be posted with an updated effective date. Continued use constitutes acceptance." },
      { heading: "Governing Law", body: "These Terms are governed by the laws of the jurisdiction in which Amplivanta is established, without regard to conflict-of-laws principles." },
      { heading: "Contact Us", body: "Questions about these Terms can be directed to legal@amplivanta.com." },
    ],
  },
  dpa: {
    breadcrumbLabel: "Data Processing Agreement",
    title: "Data Processing Agreement",
    intro: "This Data Processing Agreement (“DPA”) forms part of the agreement between Amplivanta and Customer and reflects the parties’ commitments regarding the processing of personal data in connection with the Services.",
    updated: "August 14, 2026",
    sections: [
      { heading: "Definitions", body: "Terms such as “personal data”, “processing”, “controller”, and “processor” have the meanings given under applicable data protection laws, including the GDPR where relevant." },
      { heading: "Roles of the Parties", body: "Customer is the controller and Amplivanta is the processor of personal data processed on Customer’s behalf in providing the Services." },
      { heading: "Scope & Purpose of Processing", body: "Amplivanta processes personal data only on documented instructions from Customer and for the purpose of providing and improving the Services." },
      { heading: "Sub-processors", body: "Customer authorizes Amplivanta to engage sub-processors. We maintain a current sub-processor list and impose data-protection obligations on each sub-processor consistent with this DPA." },
      { heading: "Security Measures", body: "Amplivanta implements appropriate technical and organizational measures to protect personal data, including encryption in transit and at rest, access controls, and monitoring." },
      { heading: "International Transfers", body: "Where personal data is transferred internationally, appropriate safeguards such as Standard Contractual Clauses are applied." },
      { heading: "Data Subject Requests", body: "Amplivanta assists Customer, taking into account the nature of processing, in responding to requests from data subjects to exercise their rights." },
      { heading: "Data Breach Notification", body: "Amplivanta will notify Customer without undue delay after becoming aware of a personal data breach affecting Customer data." },
      { heading: "Return & Deletion", body: "Upon termination, Amplivanta will delete or return personal data in accordance with Customer instructions and applicable retention obligations." },
      { heading: "Contact", body: "Data protection inquiries can be directed to privacy@amplivanta.com." },
    ],
  },
  "partner-terms": {
    breadcrumbLabel: "Partner Program Terms",
    title: "Partner Program Terms & Conditions",
    intro: "These Partner Program Terms & Conditions govern participation in the Amplivanta Partner Program. By applying or participating you agree to these terms.",
    updated: "August 14, 2026",
    sections: [
      { heading: "Program Overview", body: "The Partner Program enables approved agencies, consultants, technology providers, and solution experts to collaborate with Amplivanta to deliver value to mutual customers." },
      { heading: "Eligibility & Approval", body: "Participation is subject to application, review, and approval by Amplivanta. We may accept or decline applications at our discretion." },
      { heading: "Partner Responsibilities", body: "Partners agree to represent Amplivanta accurately and ethically, comply with applicable laws, and act in the best interests of mutual customers." },
      { heading: "Brand & Marketing Use", body: "Partners may use approved Amplivanta brand assets only in accordance with our brand guidelines and must not make misleading claims." },
      { heading: "Compensation & Referrals", body: "Any referral fees, commissions, or benefits are governed by the specific partnership tier and any separate written agreement." },
      { heading: "Confidentiality", body: "Partners must protect confidential information shared in connection with the program and use it solely for program purposes." },
      { heading: "Term & Termination", body: "Either party may terminate participation with notice. Amplivanta may suspend or remove partners for violations of these terms." },
      { heading: "Disclaimers", body: "Participation does not create an agency, joint venture, or employment relationship. The program is provided without warranties except as required by law." },
      { heading: "Changes", body: "We may update these terms from time to time. Continued participation constitutes acceptance of the updated terms." },
      { heading: "Contact", body: "Questions about the Partner Program can be directed to partners@amplivanta.com." },
    ],
  },
  "affiliate-terms": {
    breadcrumbLabel: "Affiliate Program Terms",
    title: "Affiliate Program Terms & Conditions",
    intro: "These Affiliate Program Terms & Conditions govern participation in the Amplivanta Affiliate Program. By applying or participating you agree to these terms.",
    updated: "August 14, 2026",
    sections: [
      { heading: "Program Overview", body: "The Affiliate Program lets approved affiliates earn commission by referring businesses to Amplivanta through unique tracking links." },
      { heading: "Eligibility", body: "The program is free to join and open to a variety of affiliates. Participation is subject to application and approval, and there are no minimum traffic or sales requirements." },
      { heading: "Commissions", body: "Affiliates earn 20% commission on eligible paid subscriptions for up to 12 months, subject to valid referrals, refunds, and chargebacks." },
      { heading: "Referral Tracking", body: "Referrals are tracked via a 90-day cookie window from the first click. Amplivanta’s tracking system is the system of record for attribution." },
      { heading: "Promotion Guidelines", body: "Affiliates must promote Amplivanta honestly and ethically, must not use misleading claims or unauthorized brand terms, and may not bid on Amplivanta brand keywords or trademarks." },
      { heading: "Payouts", body: "Payouts are made on the published schedule and are subject to valid referrals, minimum thresholds, refunds, and chargebacks." },
      { heading: "Prohibited Conduct", body: "Self-referrals, spam, incentivized clicks, and fraudulent activity are prohibited and may result in forfeiture of commissions and removal from the program." },
      { heading: "Term & Termination", body: "Either party may terminate participation at any time. Amplivanta may suspend or remove affiliates for violations of these terms." },
      { heading: "Changes", body: "We may update these terms from time to time. Continued participation constitutes acceptance of the updated terms." },
      { heading: "Contact", body: "Questions about the Affiliate Program can be directed to affiliates@amplivanta.com." },
    ],
  },
};
